### ISSUE TITLE
avatar context-awareness

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#101]
# Context Awareness in Avatars/Intelligences

Deprecated

## tasks

- [ ] create array of avatars in object (here `core.mjs`) to `this.#avatar` which will refer to the _active_ avatar
  - [x] set `this.avatar` identifies the active avatar and receives `_config` object, which has either `key` property or `context` property
    - [x] key: attempts to pull and further instantiate if necessary from 1) `this.avatars` by key 2) cosmos, 3) generate, which requires `context` property, and this to be missing or `undefined`
    - [ ] context: base object definition and record notes, as logic decisions here are particularly important
  - [x] no set for `this.avatars` as will be managed via the effective setting/usage of `this.avatar`
- [x] create event hooks in avatar and/or factory (session?)
- [ ] #103

## notes

This may be gently covered elsewhere, but here's the thinking:
- an avatar is a compilation of several things
  - user-input
    - usage + personalization: the ways in which one _uses_ MyLife itself shapes the tone and gesture for the avatar, ergo be or turn good!
  - Cosmos core elements (underlying asset that is being intelligenced, from consent to object to person)
  - Cosmos avatar elements (by id)
  - openai (or other) assistant tech
- Events to which context awareness may be attached/set (prior to birth is consent to bear)
  - onBirth(): Avatar creation/recreation
    - not surprisingly, all activities go into setting params
    - born with 3x questions (with self-generated id and category flag), stored in [], that it must pose to member, here based on fundamental human definition category data
  - onAwakening(): returned from db elements and external API
    - restore
    - ensure population (or repop) questions
  - onAnswering(): post-chat response (i.e., some require return, some can be sent off without await)
    - review follow-ons, see if any germaine to content
    - if so, add as message to response--flag
    - if flagged, review answer content, and if appropriate, update category (or create new, but that is post-alpha) locally and in Cosmos
      - given validity, remove question and either generate new, or wait for sleep if appropriate
  - onSleep(): probably not self-enforced at first, but via garbage collection-type activities, not for alpha
    - summarizes daily content from session (consents, messages, etc.)
    - compares summary (or complete list) against questions[]
      - if complete, removes questions from questions Cosmos array, creates new one from same data above
    - identifies and summarizes any questions/knowledge gaps from daily activity
    - posts to Cosmos
  - onRetire()
    - summarize self and report/distribute summary data
