### ISSUE TITLE
Selecting bots needs codification and revamp

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#286]
## todo
- [x] Default to Member Avatar
- [x] Add speaker Icons to Agent Chat Bubbles
  - [x] `members.mjs::mAddMessage`
    - [x] rollover of icon spurs title for now (think popup comic dialog box)
    - [x] only add on agent - with default for unknown thumb?
  - [x] css
    - [x] update styles for agent-bubble
    - [x] create styles for bot-icon

## notes
- Special login greeting (covered in #422 )
