### ISSUE TITLE
Memory Incomplete + Versioning

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#314]
# Memory item versioning

This began as: Platform or Member should be able to mark a memory as `incomplete`
Makes sense and what it will lead to is some sense of versioning in the end, though this build will be focused only on a default "incomplete" flag on the interface and datacore

## todo

- [x] frontend
  - [x] item popup should incorporate a true false field entitled `memory incomplete`, inverted to always default true
  - [x] Evaluate Button (suggestions for improving memory)
- [x] backend
  - [x] `mylife-avatar::item()` function
    - [x] DELETE
    - [x] POST (create)
    - [x] PUT (update)
    - [x] GET
  - [x] create core `item` class and extenders
    - [x] Memory
    - [x] Entry
  - [x] add to item payload & database `itemComplete` flag (eventually its own object node or doc) and version
  - [x] `#complete` boolean for now more as a public/private availability toggle, meaning it only populates defaults, member still needs to click consent
  - [x] `version` will present a fuller numeric picture, but everything will just be version 1.0 for now (note already there's room for arrays of versions, i.e., versions other individual members have experienced)
    - [x] proposal: first number of version is member-driven, second is MyLife Interactions
