### ISSUE TITLE
Interactive editing memory shows "I'm sorry, Something happened with my server connection..."

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#369]
Steps to reproduce
====================
Click on scrapbook.
Click on Memory bar.
Click on desired Memory.
Memory popup is open.
Click on rotating teal shadow text.
Memory popup is closed.
Ensure Active: "<Memory title>" above the chat is shown to the user.
Update the memory to add new content to the memory.
**Actual result:**
Chat window shows "I'm sorry, Something happened with my server connection, please type `try again` to try again."

**Expected result:**
Chat window should indicate user that the memory is updated.

100% reproducible with v.0.0.21

Refresh the memories
Memory is updated although above message is shown to the user. This part is working as expected.

**Comment by Vudum** [comment]
FYI @Mookse .

**Comment by Mookse** [comment]
@Vudum Great catch and a deep issue where I've miscoded the way I manage calls when they are sequential to OpenAI; this is a larger fix that will also address something with relive memories - this might take me the week to fix, but I'm on it

This one remains an unfixed bug for internal testing; it's not 100% recurring and there may be multiple pathways to fix... I should say that I will and have added more protection so that the system will respond with some status as to where it failed

## Discovery

- no error is thrown
- seems to either timeout or just fail to execute instructions correctly on GPT end
  - this can be corrected by compensating on the code and instruction end to ensure that the GPT is not unclear where to go after `getSummary` which it executes in all cases
- idea is that I will create backup responses to be available to payload that articulates the point in the process things went wrong. Given that we don't have full replicability (very often this works fine), this should be considered very effective error control

## Todo

- [ ] manage linear calls inside of MyLife (which makes it more extensible to less functional models)
- [ ] mRunFinish is in a `requires_action` state trying to ask it's second request... often it worked, perhaps this one was unknown?
- [ ] could isolate updateSummary to require an alternate system thread to manage this conversation (just like obscure)
