### ISSUE TITLE
Diary Bot Cover Art

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#381]
# Diary Bot Cover Art
Session FIVE of the Diary Bot Series will cover the building of the frontend to accommodate the internal, alas teamless Diary Bot.

## Tasks

- [x] Modify HTML
  - [x] `_bots.html` return of diary bot container HTML
  - [x] Include button for `Getting Started`
  - [x] Allow `entry`: mAvailableCollections allows; `updated _bots.html` to include
- [x] Data
  - [x] create initial Diary Bot Phantasm, direct in MyLife data
    - [x] Spritz
  - [x] Create Assistant(s) in LLM
    - [x] Spritz by hand
- [x] Bot Container
  - [x] options
  - [x] `Getting Started` functionality in `bots.mjs`
  - [x] cases (in code building)
- [x] Scrapbook/Items
  - [x] manage forms of `entry` (journal, diary, financial, etc.)
  - [x] `obscure` function: Button on Entry Item
- [x] Frontend Assets
  - [x] thumbnail icon: `views\assets\png\diary-thumb.png`
  - [x] CSS
    - [x] `collection-popup-entry`
    - [x] `improve-entry-container`
    - [x] `improve-entry-lane`
    - [x] `obscure-button`
    - [x] `experience-entry-container`
    - [x] `experience-entry-explanation`
    - [x] `experience-entry-button`
- [x] `obscure` call in `members.mjs`

**Comment by Mookse** [comment]
# MyLife General  Functioneer

## Instructions

I perform several basic but key functions for the MyLife Services Platform where members can collect, curate, relive and share their memories and other cherished stories with posterity.

### Key Functions

#### Obscure
When a request begins with the line: "OBSCURE:\n", I take the text that follows and remove all of the human name references and replace them with a single capitalized letter. Example: "Erik told me..." transforms to "E told me...". Leave non-human proper nouns alone. I return the payload as a JSON object with a single node: `obscuredSummary`
