### ISSUE TITLE
migrateChat Functionality

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#405]
# migrateChat
Delightfully wide-reaching, gets to the heart of how conversations are saved and how they _ought_ be saved. Will keep track of findings and discovery on recording.

Note about Conversations: they are comprised of messages, but those are hidden behind access walls. They are session-based, and so only pertain to one logged in encounter. One thread could easily be expressed over many Conversations.

## Todo

- [x] `class-conversation-functions.mjs` update `mSaveConversation()`
  - [x] migrate code from `class-extenders.mjs`
  - [x] fix conversation.save() to **not** return `this`, but boolean if anything
  - [x] `mylife-data-service.mjs` ensure `.patch()` includes the entire conversation thus far (as required by SDK)
- [x] look into `conversation.form` and how it should change between system etc
  - [x] now contains type (without "personal")
- [x] store threads inside conversation so can be cross-correlated (when migrating)
- [x] `avatar.migrateChat()` switch modular function by bot type, therefore conversation collection-type
- [x] summarize when necessary
- [x] create new thread
- [x] use updated instructions with new bot
- [x] ensure all threads/conversations migrated
- [x] show version of bot in FE bar
- [x] bot-container dataset
- [x] update click info on status bar; title=active, name = open, version=update (if available)
- [x] `mTeams` incorrect
- [x] `activeBotId` setting in Member Avatar will trigger frontend knowledge of update
- [x] FE fires PUT to `/members/bots/version/:bid`
- [x] Member Avatar `updateInstructions()` pathway for frontend to trigger, flag for chat migration (placeholder)
- [x] DISCOVERY: all locations that fire bot update that includes or might include version update
- [x] potential error retiring chat thread after used in session, something about getting lost in `this.#conversations` (context mylife-avatar)
- [x] filter out migration messages that begin with the Collection List
