### ISSUE TITLE
Migrate Conversation from Avatar to Bot

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#406]
# Move Conversation to Bot
As architecture turned out, conversations (which could and should be brought into full objects or agents) are best utilized as BOT objects, certainly (usually, think Diary Bot) accessible to Member Avatar inspection, but not housed independently and disconnected in its general memory, as it is now in `this.#conversations`, a remnant of pre-thread coding

## todo

- [x] **discovery**: given that we have 3 types of factories, and 2 types of avatars, 2 types of core, it might be that we store conversations differently, for instance, Q would need to have access to conversations, not bot (as bot cannot have single thread)
- [x] **discovery**: why use this.#conversations finding? can just use bot?
- [x] move all `this.#conversations` to `class Q`
- [x] align normal and overloaded `chat()` function in `mylife-avatar.mjs`
- [x] `functions.mjs` tailor to new mechanic
- [x] deprecate `conversation.bot_id = botId` and  `conversation.llm_id = bot_id` in `mylife-avatar.mjs`
- [x] create `BotAgent` from `mylife-factory.mjs`
  - [x] build class structure
  - [x] init()
  - [x] `mBot` move
  - [x] class `Bot`
  - [x] move `mBotInstructions`
  - [x] move `mGetAIFunctions` from `mylife-factory.mjs`
  - [x] move `mGetGPTResources`
  - [x] move `mCreateBotLLM`
  - [x] move `mAI_openai`
  - [x] move `mCreateBot` -> `mBotCreate`
  - [x] move `updateBot`
  - [x] address `challengeAccess`
- [x] `conversation.json` updates (not yet ready for class - determine after Pilot review)
- [x] **refactor**: Conversation botId/bot_id
- [x] Incorporate `runs` in Conversation Object
  - [x]  `run_id` as comma-delimited string when executed successfully?
- [x] BotAgent functions
  - [x] initial active bot = personal avatar
  - [x] set active bot
  - [x] route chats, allow routes to Bot/activeBot
  - [x] `chat()` = create conversations on-initial demand with correct formatting to reside primarily inside of Bot instance
- [x] create `BotAgent` from `mylife-avatar.mjs`
  - [x] `this.#bots` or `#bots`
  - [x] `#activeBotId`
  - [x] `getGreeting` and `mGreeting`
  - [x] `createBot`
  - [x] `createConversation`
  - [x] `chat()` functionality using Bot class
  - [x] `mCallLLM` -> current references should leverage #botAgent (may require numerous pipeline param additions)
    - [x] `obscure()`
    - [x] `summarize()`
    - [x] `mReliveMemoryNarration` => `liveMemory()`
  - [x] `migrateBot`
  - [x] `mMigrateChat`
  - [x] `retireBot` - becomes `deleteBot()`
  - [x] `retireChat`
- [x] Test and Review
  - [x] obscure()
  - [x] summarize()
  - [x] migrate chat
  - [x] retire bot => changed to `/bots/:bid` DELETE method
  - [x] Relive (all variants)
