### ISSUE TITLE
Print Memory Functionality

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#429]
# Make Memory
## PRINT Memory Functionality
Needing some sort of "That's all I have to say about that" protocol into the interface requires something in addition to, or a coopting of the `send` button - I would want to provide an alternative **hard** return button that indicates you are finished discussing that memory. 
It has **not** been effective to leave this to the LLM via instructions, nor would I ever expect it to compete with member clarity (even if a keyword, such as "done" or "print"-- I do like print...), so...
I'm proposing to utilize the ACTIVE MEMORY BAR to 
**Note:** The frontend and backend concerns retain independence. If we choose to alter the interface, there is likely no backend impact, so long as the ## PRINT protocol is followed. I have altered the name of the function from "Make Memory" to PRINT MEMORY as the double entendre is desirable for a companionable frontend, backend confusion is widely undesirable, and print a memory tends to work even without being directly addressed in LLM `instructions`

- addresses concerns #388 

### Todo

- [x] frontend
  - [x] fix: close button missing in long titles on ACTIVE bar
  - [x] `members.html`: incorporate active bar - very likely that multiple bots will want to use this as a widget, so begin separation at top-level persistent definition
  - [x] `members.mjs`:
    - [x] display (when to show/hide? definition inside bot-type? yes?) variable=itemAccess {Boolean} = true
    - [x] setActiveAction(): function that will accept population mechanisms for action/active bar to create default as proxy for primary action (here, Make a Memory from our recent conversation)
  - [x] `bots.mjs`
    - [x] getAction() - based on bot, call the default the default action, currently only biog
    - [x] _Make a Memory_ (which can have a GO button on it to force create, as per bubble-tab?) when biographer is selected
    - [x] receive command: createItem.
- [x] backend
  - [x] clean up collection returns (currently not pruned): { id, }
  - [x] change unique summary function to itemSummary()
    - [x] `mylife-factory.mjs` - move to `mylife-avatar.mjs` -> `bot-agent.mjs.Bot`
      - [x] summary (bot-agent)
      - [x] entry (ends at avatar)
      - [x] story  (ends at avatar)
  - [x] include `updatesummary` to same managerial endpoint? NO, can be dealt with independently in refactor
  - [x] instructions: explain in both avatar and biographer functionality and startup
    - [x] assistantType (instead of form
    - [x] being = story (until deprecating)
    - [x] form = diary/journal/memory
    - [x] type = memory (entry)
