### ISSUE TITLE
Version 0.0.28 Updates

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#436]
# MyLife Member Services Platform Version 0.0.28
This is the last full version (I mean it this time!) before the services get trimmed to only alpha functionality and critical updates. At this point, core functionality is working beyond specification, so I'm excited. There are always hiccups now and again, but most of the hatches have been battened, and we're ready to rock.

## Todo

- [x] thread migration failed for bot: c32a5540-29d8-4bb5-8a3e-1fb29692b1b4; add logs to display, might have only been an internal error, new thread was created and looked fine when inspected
- [x] #362 
- [x] #325
- [x] on active item, set correct bot
- [x] direct updates altering assistantType
- [x] title change error: not taking on server through interface channels nor bot, must have been stripped
- [x] #314 
- [x] #425 
- [x] #427
