### ISSUE TITLE
Version 0.0.29 Updates

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#440]
# MyLife Member Services Platform Version 0.0.29
This is the version that gets trimmed to only alpha functionality and critical updates, potentially including numerous updates to the actual functionality of the bots as regards how they present in front of actual users.

## Todo

- [x] remove frontend thumb from user
- [x] add Q thumb on site
- [x] Startup routine for each bot (pull hard coded from server, can right in sectional html for ease right now) - include frontend instructions to demonstrate interops
- [x] #421 
- [x] #393 
- [x] #449
- [x] Return guests.mjs to point where it can call new routines
- [x] #439
- [x] #442 
- [x] #263
